###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "headline": {
        "query": "Shape of you"
      }
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "headline": {
        "query": "Shape of you"
      }
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "Michelle Obama",
      "fields": [
        "headline",
        "short_description",
        "authors"
      ]
    }
  }
}

### Per-field boosting with carat(^) symbol
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "Michelle Obama",
      "fields": [
        "headline^2",
        "short_description",
        "authors"
      ]
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "party planning",
      "fields": [
        "headline^2",
        "short_description"
      ],
      "type": "phrase"
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "headline": "Michelle Obama"
    }
  },
  "aggs": {
    "category_mentions": {
      "terms": {
        "field": "category",
        "size": 100
      }
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "headline": "Michelle Obama"
          }
        },
        {
          "match": {
            "category": "POLITICS"
          }
        }
      ]
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "headline": "Michelle Obama"
          }
        }
      ],
      "must_not": [
        {
          "match": {
            "category": "WEDDINGS"
          }
        }
      ]
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "headline": "Michelle Obama"
          }
        }
      ],
      "should": [
        {
          "match_phrase": {
            "category": "BLACK VOICES"
          }
        }
      ]
    }
  }
}

###
GET {{url}}/news_headlines/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "headline": "Michelle Obama"
          }
        }
      ],
      "filter": {
        "range": {
          "date": {
            "gte": "2014-03-25",
            "lte": "2016-03-25"
          }
        }
      }
    }
  }
}